// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdghO6XOHUeJwkSKffVfmmFMmZTK58rJk',
    appId: '1:285882102553:web:c6dacb0172099db9498b88',
    messagingSenderId: '285882102553',
    projectId: 'task-app-8a439',
    authDomain: 'task-app-8a439.firebaseapp.com',
    storageBucket: 'task-app-8a439.firebasestorage.app',
    measurementId: 'G-6WSHEWPGF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPTqUzYoqQ_-LHzRLP0SQUFqBv2IFMpAA',
    appId: '1:285882102553:android:2d74072d87c6eac8498b88',
    messagingSenderId: '285882102553',
    projectId: 'task-app-8a439',
    storageBucket: 'task-app-8a439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXcmyfAyBCCF0ZRVlf-eMLvl0gGXoyEo',
    appId: '1:285882102553:ios:9ec571ecd0fe50e7498b88',
    messagingSenderId: '285882102553',
    projectId: 'task-app-8a439',
    storageBucket: 'task-app-8a439.firebasestorage.app',
    androidClientId: '285882102553-sq1pp3ddeiho9nchbkkvbc7tlg8s9ruf.apps.googleusercontent.com',
    iosClientId: '285882102553-3uru14tqajqf7s36ehmbjc62dt57p1tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxXcmyfAyBCCF0ZRVlf-eMLvl0gGXoyEo',
    appId: '1:285882102553:ios:9ec571ecd0fe50e7498b88',
    messagingSenderId: '285882102553',
    projectId: 'task-app-8a439',
    storageBucket: 'task-app-8a439.firebasestorage.app',
    androidClientId: '285882102553-sq1pp3ddeiho9nchbkkvbc7tlg8s9ruf.apps.googleusercontent.com',
    iosClientId: '285882102553-3uru14tqajqf7s36ehmbjc62dt57p1tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdghO6XOHUeJwkSKffVfmmFMmZTK58rJk',
    appId: '1:285882102553:web:ff4a72bffaf10f10498b88',
    messagingSenderId: '285882102553',
    projectId: 'task-app-8a439',
    authDomain: 'task-app-8a439.firebaseapp.com',
    storageBucket: 'task-app-8a439.firebasestorage.app',
    measurementId: 'G-WKF87J8TG8',
  );

}